In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv

In [5]:
df = pd.read_csv('spam.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df.shape

(5572, 2)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=0.2,random_state=1)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [10]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = v.fit_transform(emails)
emails_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 6)>

In [11]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [12]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [13]:
pd.DataFrame(emails_cv.toarray(), columns=v.get_feature_names_out())

   20  discount  hey  mohan  reward  upto
0   1         1    0      0       1     1
1   0         1    1      1       0     1

In [17]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58978 stored elements and shape (4457, 7711)>

In [18]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
X_train_cv.shape

(4457, 7711)

In [20]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [21]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [22]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

,00,000,008704050406,0121,01223585236,01223585334,0125698789,02,0207,02072069400,...,zed,zeros,zhong,zindgi,zoe,zoom,zouk,zyada,èn,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
v.vocabulary_

{'hi': 3423,
 'where': 7442,
 'are': 1051,
 'you': 7674,
 'we': 7370,
 're': 5564,
 'at': 1119,
 'and': 963,
 'they': 6794,
 'not': 4813,
 'keen': 3906,
 'to': 6889,
 'go': 3153,
 'out': 4985,
 'kind': 3940,
 'of': 4872,
 'am': 937,
 'but': 1578,
 'feel': 2795,
 'shouldn': 6077,
 'so': 6230,
 'can': 1632,
 'tomo': 6910,
 'don': 2408,
 'mind': 4474,
 'do': 2377,
 'if': 3593,
 'home': 3469,
 'then': 6782,
 'come': 1908,
 'down': 2433,
 'within': 7511,
 'min': 4471,
 'when': 7438,
 'guys': 3278,
 'getting': 3116,
 'back': 1196,
 'said': 5845,
 'were': 7419,
 'thinking': 6804,
 'about': 759,
 'staying': 6408,
 'for': 2927,
 'mcr': 4392,
 'tell': 6710,
 'my': 4650,
 'bad': 1199,
 'character': 1738,
 'which': 7448,
 'dnt': 2376,
 'lik': 4108,
 'in': 3633,
 'me': 4393,
 'll': 4156,
 'try': 7007,
 'change': 1730,
 'lt': 4243,
 'gt': 3254,
 'add': 813,
 'tat': 6671,
 'new': 4743,
 'year': 7650,
 'resolution': 5708,
 'waiting': 7308,
 'ur': 7147,
 'reply': 5688,
 'be': 1270,
 'frank': 2963,
 'good': 3177,
 'morning': 4577,
 'leaving': 4063,
 'house': 3510,
 'now': 4828,
 'hey': 3419,
 'watching': 7353,
 'movie': 4595,
 'tonight': 6918,
 'prob': 5403,
 'early': 2507,
 'da': 2145,
 'al': 901,
 'above': 761,
 'camera': 1629,
 'awarded': 1171,
 'sipix': 6131,
 'digital': 2321,
 'call': 1609,
 '09061221066': 186,
 'fromm': 3010,
 'landline': 4006,
 'delivery': 2241,
 '28': 374,
 'days': 2185,
 'fyi': 3046,
 'gonna': 3175,
 'sporadically': 6357,
 'starting': 6399,
 'like': 4109,
 'bc': 1258,
 'doin': 2398,
 'this': 6809,
 'shit': 6050,
 'stop': 6444,
 'knowing': 3961,
 'well': 7410,
 'mmm': 4520,
 'thats': 6770,
 'better': 1330,
 'got': 3194,
 'roast': 5770,
 'had': 3289,
 'few': 2809,
 'drinks': 2457,
 'indian': 3656,
 'want': 7328,
 'tel': 6706,
 'one': 4918,
 'thing': 6799,
 'should': 6076,
 'mistake': 4508,
 'is': 3746,
 'the': 6771,
 'message': 4445,
 'that': 6768,
 'sent': 5976,
 'happened': 3324,
 'here': 3409,
 'while': 7449,
 'adventuring': 839,
 'on': 4914,
 'way': 7365,
 'email': 2569,
 'id': 3581,
 'soon': 6271,
 'wen': 7413,
 'lovable': 4221,
 'bcums': 1267,
 'angry': 968,
 'wid': 7467,
 'take': 6645,
 'it': 3757,
 'seriously': 5985,
 'coz': 2050,
 'being': 1306,
 'most': 4581,
 'childish': 1791,
 'true': 6999,
 'showing': 6086,
 'deep': 2217,
 'affection': 849,
 'care': 1657,
 'luv': 4258,
 'kettoda': 3917,
 'manda': 4330,
 'have': 3354,
 'nice': 4755,
 'day': 2184,
 'life': 4099,
 'alle': 921,
 'mone': 4556,
 'eppolum': 2614,
 'oru': 4972,
 'pole': 5266,
 'allalo': 919,
 'there': 6788,
 'size': 6146,
 'elephant': 2562,
 'tablets': 6633,
 'shove': 6079,
 'um': 7075,
 'up': 7129,
 'ass': 1104,
 'brainless': 1482,
 'baby': 1190,
 'doll': 2402,
 'vehicle': 7211,
 'sariyag': 5872,
 'drive': 2458,
 'madoke': 4297,
 'barolla': 1229,
 'just': 3876,
 'seeing': 5946,
 'your': 7678,
 'missed': 4500,
 'dear': 2197,
 'brother': 1526,
 'gr8': 3206,
 'dun': 2489,
 'say': 5889,
 'hor': 3491,
 'already': 929,
 'only': 4923,
 '500': 537,
 'free': 2972,
 'text': 6743,
 'msgs': 4612,
 'ok': 4895,
 '80488': 647,
 'credit': 2074,
 'account': 787,
 'won': 7539,
 'as': 1087,
 'valued': 7194,
 'vodafone': 7266,
 'customer': 2130,
 'our': 4983,
 'computer': 1946,
 'has': 3340,
 'picked': 5180,
 'win': 7481,
 '150': 297,
 'prize': 5400,
 'collect': 1896,
 'easy': 2517,
 '09061743386': 191,
 'think': 6801,
 'syllabus': 6619,
 'networking': 4736,
 'job': 3831,
 'wat': 7349,
 'decision': 2210,
 'much': 4623,
 'buzy': 1587,
 'times': 6859,
 'today': 6895,
 'umma': 7076,
 'ask': 1096,
 'them': 6779,
 'speed': 6321,
 'means': 4399,
 'still': 6431,
 'teju': 6705,
 'auction': 1139,
 'round': 5795,
 'highest': 3428,
 'bid': 1345,
 '54': 557,
 'next': 4751,
 'maximum': 4385,
 '71': 613,
 'send': 5968,
 'bids': 1346,
 '10': 249,
 '83383': 668,
 'luck': 4248,
 'bored': 1437,
 'housewives': 3511,
 'chat': 1752,
 'date': 2176,
 '0871750': 131,
 '77': 624,
 '11': 263,
 'bt': 1540,
 'national': 4688,
 'rate': 5548,
 '10p': 260,
 'from': 3009,
 'landlines': 4008,
 'derp': 2264,
 'worse': 7570,
 'dude': 2482,
 'who': 7454,
 'always': 935,
 'wants': 7332,
 'party': 5071,
 'or': 4950,
 'files': 2831,
 'complaint': 1933,
 'three': 6826,
 'drug': 2468,
 'abusers': 770,
 'he': 3363,
 'lives': 4153,
 'with': 7509,
 'give': 3136,
 'thanks': 6760,
 'no': 4779,
 'pic': 5178,
 'please': 5229,
 'billion': 1353,
 'classes': 1836,
 'right': 5752,
 'horrible': 3495,
 'bf': 1338,
 'hungry': 3544,
 'yetty': 7664,
 'number': 4839,
 'pls': 5237,
 'what': 7432,
 'mean': 4395,
 'was': 7342,
 'left': 4066,
 'too': 6922,
 'check': 1762,
 'cos': 2022,
 'working': 7560,
 'sucks': 6527,
 'planned': 5217,
 'yo': 7669,
 'valentine': 7188,
 'aren': 1053,
 'oh': 4890,
 'howda': 3515,
 'gud': 3260,
 'mathe': 4372,
 'en': 2579,
 'samachara': 5858,
 'chikku': 1789,
 'nokia': 4789,
 'motorola': 4589,
 'upto': 7146,
 '12mths': 283,
 '2price': 409,
 'linerental': 4124,
 'net': 4729,
 'mins': 4485,
 '100txt': 255,
 'mth': 4615,
 'tooth': 6928,
 'mobileupd8': 4536,
 '08001950382': 52,
 '2optout': 407,
 'd3wv': 2144,
 'edison': 2531,
 'rightly': 5754,
 'fool': 2919,
 'more': 4573,
 'questions': 5505,
 'than': 6756,
 'wise': 7500,
 'man': 4324,
 'answer': 982,
 'know': 3960,
 'why': 7462,
 'all': 917,
 'us': 7161,
 'speechless': 6320,
 'during': 2494,
 'viva': 7262,
 'gm': 3147,
 'gn': 3149,
 'ge': 3087,
 'gnt': 3151,
 'symptoms': 6622,
 'love': 4222,
 'listening': 4142,
 'songs': 6267,
 'get': 3108,
 'stopped': 6449,
 'see': 5944,
 'name': 4669,
 'beloved': 1316,
 'sir': 6133,
 'goodmorning': 3182,
 'once': 4917,
 'real': 5574,
 'tho': 6815,
 'even': 2649,
 'cook': 2004,
 'whole': 7456,
 'electricity': 2561,
 'alrite': 931,
 'jod': 3834,
 'hows': 3518,
 'revision': 5740,
 'goin': 3163,
 'keris': 3916,
 'bin': 1358,
 'smidgin': 6199,
 'wanna': 7326,
 'cum': 2116,
 'over': 5003,
 'after': 859,
 'college': 1901,
 'xx': 7625,
 'ugh': 7065,
 'hopefully': 3488,
 'asus': 1117,
 'ppl': 5325,
 'dont': 2412,
 'randomly': 5542,
 'reformat': 5630,
 'serving': 5989,
 'doing': 2400,
 'imagine': 3611,
 'finally': 2843,
 'sink': 6129,
 'into': 3712,
 'bath': 1244,
 'put': 5484,
 'through': 6830,
 'paces': 5022,
 'maybe': 4388,
 'having': 3359,
 'eat': 2518,
 'before': 1295,
 'also': 932,
 'cage': 1601,
 'cock': 1881,
 'surrounded': 6584,
 'by': 1594,
 'water': 7355,
 'reminding': 5669,
 'owns': 5016,
 'enjoy': 2593,
 'cuck': 2109,
 'promise': 5427,
 'treat': 6980,
 'bet': 1326,
 'will': 7478,
 'wait': 7305,
 'cornwall': 2014,
 'hope': 3486,
 'isn': 3752,
 'rock': 5773,
 'night': 4763,
 'shite': 6051,
 'anyway': 1004,
 'going': 3164,
 'kip': 3947,
 'speak': 6311,
 'thank': 6759,
 'skyped': 6160,
 'wit': 7508,
 'kz': 3979,
 'sura': 6574,
 'didnt': 2307,
 'pleasure': 5232,
 'company': 1926,
 've': 7208,
 'given': 3137,
 'ultimatum': 7074,
 'countin': 2035,
 'aburo': 769,
 'interflora': 3704,
 'late': 4027,
 'order': 4958,
 'flowers': 2897,
 'christmas': 1818,
 '0800': 46,
 '505060': 539,
 'place': 5208,
 'midnight': 4458,
 'tomorrow': 6912,
 'time': 6858,
 'xin': 7620,
 'hostel': 3501,
 'wasn': 7344,
 'available': 1156,
 'washob': 7343,
 'nobbing': 4781,
 'last': 4024,
 'nickey': 4758,
 'platt': 5220,
 'instead': 3694,
 'registered': 5641,
 'sinco': 6123,
 'payee': 5100,
 'log': 4172,
 'icicibank': 3578,
 'com': 1905,
 'enter': 2599,
 'urn': 7159,
 'confirm': 1960,
 'beware': 1336,
 'frauds': 2967,
 'share': 6022,
 'disclose': 2348,
 'anyone': 996,
 'sexy': 6001,
 'buns': 1562,
 'told': 6903,
 'adore': 827,
 'loverboy': 4228,
 'remember': 5662,
 'sister': 6136,
 'law': 4041,
 'those': 6816,
 'meatballs': 4404,
 'grins': 3237,
 'babe': 1188,
 'important': 3624,
 'prevent': 5378,
 'dehydration': 2230,
 'giving': 3139,
 'her': 3408,
 'enough': 2598,
 'fluids': 2899,
 'smsservices': 6215,
 'yourinclusive': 7680,
 'credits': 2076,
 'goto': 3197,
 'www': 7610,
 'comuk': 1948,
 'login': 4175,
 '3qxj9': 468,
 'unsubscribe': 7124,
 'extra': 2722,
 'charge': 1740,
 'help': 3396,
 '08702840625': 83,
 '220': 356,
 'cm2': 1868,
 '9ae': 735,
 'japanese': 3795,
 'proverb': 5447,
 'none': 4795,
 'must': 4646,
 'version': 7220,
 'let': 4084,
 'him': 3432,
 'leave': 4061,
 'kerala': 3914,
 'make': 4314,
 'strike': 6469,
 'against': 866,
 'hello': 3394,
 'site': 6139,
 'download': 2434,
 'its': 3764,
 'urgent': 7151,
 'god': 3159,
 'google': 3189,
 'nearby': 4703,
 'cliffs': 1850,
 'congratulations': 1967,
 'cd': 1703,
 'vouchers': 7277,
 '125gift': 280,
 'guaranteed': 3258,
 'entry': 2608,
 '100': 250,
 'wkly': 7522,
 'draw': 2446,
 'txt': 7044,
 'music': 4643,
 '87066': 689,
 'probably': 5404,
 'money': 4557,
 'worries': 7567,
 'things': 6800,
 'coming': 1914,
 'due': 2485,
 'several': 5997,
 'outstanding': 5000,
 'invoices': 3725,
 'work': 7556,
 'did': 2305,
 'two': 7042,
 'months': 4569,
 'ago': 876,
 'seen': 5952,
 'holby': 3460,
 'online': 4922,
 'yahoo': 7636,
 'would': 7578,
 'someday': 6247,
 'any': 993,
 'file': 2830,
 'bag': 1203,
 'called': 1615,
 'find': 2846,
 'anything': 1001,
 'room': 5787,
 'adult': 835,
 '18': 313,
 'content': 1986,
 'video': 7232,
 'shortly': 6072,
 'doesnt': 2389,
 'sense': 5973,
 'unless': 7113,
 'need': 4711,
 'wikipedia': 7474,
 'contents': 1989,
 'page': 5027,
 'opinion': 4939,
 'jada': 3783,
 'kusruthi': 3977,
 'silent': 6114,
 'spl': 6342,
 'matured': 4379,
 'stylish': 6501,
 'simple': 6119,
 'xmas': 7621,
 'story': 6456,
 'peace': 5106,
 'msg': 4606,
 'miracle': 4490,
 'jesus': 3819,
 'hav': 3351,
 'blessed': 1388,
 'month': 4566,
 'ahead': 880,
 'amp': 953,
 'wish': 7501,
 'merry': 4442,
 'thanx': 6765,
 'weekly': 7397,
 'comp': 1923,
 'chance': 1729,
 'an': 959,
 'ipod': 3734,
 'pod': 5259,
 '80182': 645,
 'std': 6410,
 'apply': 1028,
 '08452810073': 69,
 'details': 2279,
 'went': 7416,
 'batt': 1248,
 'watch': 7350,
 'shop': 6062,
 'bit': 1368,
 'lor': 4201,
 'prepare': 5358,
 'pounded': 5317,
 'every': 2655,
 'taking': 6650,
 'part': 5066,
 'mobile': 4532,
 'survey': 6585,
 'yesterday': 7662,
 'texts': 6753,
 'use': 7165,
 'however': 3517,
 'txts': 7052,
 '80160': 644,
 'txt43': 7046,
 '50p': 543,
 'very': 7222,
 'inconvenient': 3647,
 'sis': 6135,
 'huh': 3536,
 'yes': 7660,
 'appt': 1038,
 'again': 865,
 'ah': 878,
 'sen': 5967,
 'selected': 5957,
 'yet': 7663,
 'keep': 3907,
 'touch': 6947,
 'easiest': 2512,
 'barcelona': 1223,
 'how': 3513,
 'ru': 5810,
 'cramps': 2060,
 'sleep': 6165,
 'anywhere': 1006,
 'damn': 2154,
 'hunting': 3548,
 'been': 1290,
 'searching': 5927,
 'words': 7555,
 'breather': 1501,
 'wont': 7546,
 'granted': 3219,
 'fulfil': 3026,
 'wonderful': 7543,
 'blessing': 1389,
 'car': 1652,
 'keys': 3920,
 'purse': 5479,
 'yun': 7692,
 'buying': 1585,
 'school': 5901,
 'offer': 4876,
 '2000': 343,
 'plus': 5242,
 'she': 6029,
 'bedroom': 1288,
 'minute': 4487,
 'sed': 5943,
 'mood': 4570,
 'came': 1628,
 'minuts': 4489,
 'latr': 4032,
 'cake': 1602,
 'wife': 7470,
 'medical': 4407,
 'missions': 4504,
 'nigeria': 4761,
 'takin': 6649,
 'shower': 6083,
 'yeah': 7649,
 'done': 2410,
 'first': 2861,
 'question': 5503,
 'reached': 5567,
 'sch': 5899,
 'winner': 7491,
 'mr': 4601,
 'foley': 2907,
 'exciting': 2686,
 'prizes': 5402,
 'eye': 2725,
 'visit': 7258,
 '82050': 655,
 'co': 1875,
 'uk': 7069,
 'hahaha': 3293,
 'brain': 1480,
 'chuckin': 1820,
 'red': 5621,
 'green': 3231,
 'black': 1375,
 'trainners': 6963,
 'save': 5884,
 'carryin': 1675,
 'bac': 1195,
 'train': 6960,
 'sure': 6575,
 'driving': 2461,
 'reach': 5565,
 'destination': 2277,
 'confuses': 1965,
 'doesn': 2388,
 'nothing': 4818,
 'scream': 5916,
 'moan': 4529,
 'bed': 1285,
 'princess': 5390,
 'wow': 7582,
 'boys': 1476,
 '2007': 348,
 'tour': 6950,
 'vip': 7250,
 'tickets': 6847,
 'pre': 5348,
 'book': 1428,
 'club': 1862,
 '81303': 653,
 'trackmarque': 6956,
 'ltd': 4244,
 'info': 3666,
 'vipclub4u': 7251,
 'mum': 4629,
 'leh': 4070,
 'possible': 5303,
 'dint': 2331,
 'slowly': 6186,
 'clean': 1840,
 'heart': 3377,
 'blood': 1401,
 'ten': 6721,
 'special': 6313,
 'people': 5120,
 'sitting': 6141,
 'ard': 1050,
 'busy': 1577,
 'weather': 7379,
 'cali': 1606,
 'great': 3229,
 'complexities': 1940,
 'move': 4592,
 'freely': 2977,
 'taxes': 6678,
 'outrageous': 4994,
 'sad': 5840,
 'missing': 4502,
 'same': 5861,
 '2p': 408,
 'per': 5122,
 'germany': 3107,
 '08448350055': 64,
 'line': 4121,
 'planettalkinstant': 5216,
 'opt': 4944,
 'may': 4386,
 'dismay': 2357,
 'many': 4339,
 'goes': 3161,
 'sip': 6130,
 'cappuccino': 1648,
 'kiss': 3949,
 'across': 798,
 'sea': 5925,
 'drink': 2454,
 'plenty': 5234,
 'believe': 1307,
 'tot': 6943,
 'thk': 6810,
 'muz': 4648,
 'tog': 6898,
 '200': 342,
 'award': 1170,
 '1000': 251,
 'cashto': 1683,
 'claim': 1829,
 '08000407165': 47,
 'getstop': 3114,
 '88222': 700,
 'php': 5173,
 'rg21': 5743,
 '4jx': 523,
 'quit': 5509,
 'hmmm': 3450,
 'jazz': 3802,
 'yogasana': 7671,
 'oso': 4974,
 'meet': 4411,
 'em': 2568,
 'lessons': 4083,
 'den': 2246,
 'playing': 5226,
 'gautham': 3075,
 'gran': 3214,
 'onlyfound': 4924,
 'afew': 846,
 'cusoon': 2126,
 'honi': 3478,
 'aight': 886,
 'mu': 4621,
 'swing': 6611,
 'somebody': 6246,
 'door': 2418,
 'sorry': 6280,
 'gone': 3173,
 'really': 5583,
 'private': 5397,
 '2003': 344,
 'statement': 6402,
 '07753741225': 28,
 'shows': 6088,
 '800': 636,
 'un': 7080,
 'redeemed': 5622,
 'points': 5263,
 '08715203677': 124,
 'identifier': 3587,
 'code': 1884,
 '42478': 488,
 'expires': 2709,
 '24': 361,
 '04': 14,
 'rite': 5765,
 'evey': 2666,
 'mnth': 4526,
 'since': 6122,
 'parents': 5059,
 'tuesday': 7020,
 'cover': 2047,
 'seems': 5951,
 'unnecessarily': 7117,
 'affectionate': 850,
 'holla': 3465,
 'cant': 1644,
 'spare': 6306,
 'off': 4874,
 'top': 6930,
 'head': 3364,
 'miles': 4465,
 'smiles': 6201,
 'made': 4295,
 'frm': 3000,
 'letters': 4087,
 'difference': 2314,
 'smile': 6200,
 'face': 2731,
 'keeps': 3909,
 'happy': 3331,
 'though': 6819,
 'away': 1172,
 'smiling': 6203,
 'nyt': 4854,
 'exhausted': 2694,
 'wine': 7487,
 'pie': 5187,
 'incredible': 3650,
 'learn': 4058,
 'truly': 7002,
 'amazing': 939,
 'blow': 1404,
 'o2fwd': 4858,
 '18p': 316,
 'mail': 4306,
 'cash': 1680,
 'balance': 1209,
 'currently': 2124,
 'pounds': 5318,
 'maximize': 4384,
 '86688': 686,
 '150p': 299,
 'cc': 1700,
 '08708800282': 91,
 'hg': 3421,
 'suite342': 6541,
 '2lands': 395,
 'row': 5798,
 'w1j6hl': 7288,
 'lot': 4209,
 'feels': 2798,
 'quiet': 5508,
 'beth': 1328,
 'aunts': 1147,
 'charlie': 1745,
 'lots': 4211,
 'helen': 3390,
 'mo': 4528,
 'needs': 4716,
 'dat': 2174,
 'vomit': 7271,
 '1st': 330,
 'week': 7393,
 'no1': 4780,
 'tone': 6913,
 '8077': 649,
 'txting': 7050,
 'mates': 4370,
 'getzed': 3117,
 'pobox': 5248,
 '36504': 447,
 'w45wq': 7292,
 '16': 308,
 'norm150p': 4806,
 'created': 2072,
 'gap': 3063,
 'between': 1333,
 'fingers': 2850,
 'comes': 1910,
 'fills': 2835,
 'gaps': 3064,
 'holding': 3463,
 'hand': 3309,
 'tiwary': 6876,
 'rcb': 5557,
 'battle': 1250,
 'bang': 1216,
 'kochi': 3966,
 'costa': 2025,
 'del': 2231,
 'sol': 6238,
 'holiday': 3464,
 '5000': 538,
 'await': 1167,
 'collection': 1899,
 '09050090044': 164,
 'toclaim': 6894,
 'sae': 5841,
 'tcs': 6688,
 'pobox334': 5251,
 'stockport': 6436,
 'sk38xh': 6149,
 'cost': 2024,
 '50': 536,
 'pm': 5245,
 'max10mins': 4382,
 'messages': 4447,
 'valid': 7190,
 'until': 7127,
 '31': 435,
 'december': 2204,
 '2005': 346,
 'unique': 7105,
 '30th': 434,
 'august': 1144,
 'areyouunique': 1057,
 'awake': 1169,
 'loving': 4232,
 'bold': 1421,
 'bb': 1253,
 'torch': 6937,
 'haf': 3291,
 'passport': 5080,
 'smth': 6216,
 'juz': 3879,
 'double': 2426,
 'orange': 4954,
 'price': 5383,
 'sonyericsson': 6269,
 '08000839402': 49,
 'or2optout': 4951,
 'hv9d': 3558,
 'miss': 4498,
 'saw': 5888,
 'persons': 5144,
 'library': 4093,
 'run': 5822,
 'walk': 7312,
 'kills': 3938,
 'ya': 7634,
 '4goten': 521,
 'bout': 1451,
 'scammers': 5894,
 'smart': 6191,
 'regular': 5645,
 'respond': 5713,
 'further': 3041,
 'prem': 5353,
 'subscription': 6516,
 'other': 4976,
 'nos': 4811,
 'used': 7166,
 'sweet': 6603,
 'wondering': 7544,
 'moment': 4551,
 'might': 4460,
 'someone': 6248,
 'because': 1280,
 ...}

In [24]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [25]:
X_test_cv = v.transform(X_test)

In [26]:
X_test_cv.toarray().shape

(1115, 7711)

In [27]:
model.score(X_test_cv, y_test)

0.989237668161435

In [28]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [29]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [30]:
emails_count = v.transform(emails)
emails_count.toarray().shape

(2, 7711)

In [31]:
model.predict(emails_count)

array(['spam', 'ham'], dtype='<U4')