In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Cancer.csv to Cancer (2).csv

In [3]:
df=pd.read_csv('Cancer.csv')
df

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,M
...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,M
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,M
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,M
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,M
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,B

In [4]:
df.isnull().sum()

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           0
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             0
fractal_dimension_mean    0
diagnosis                 0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   radius_mean             569 non-null    float64
 1   texture_mean            569 non-null    float64
 2   perimeter_mean          569 non-null    float64
 3   area_mean               569 non-null    float64
 4   smoothness_mean         569 non-null    float64
 5   compactness_mean        569 non-null    float64
 6   concavity_mean          569 non-null    float64
 7   concave points_mean     569 non-null    float64
 8   symmetry_mean           569 non-null    float64
 9   fractal_dimension_mean  569 non-null    float64
 10  diagnosis               569 non-null    object
dtypes: float64(10), object(1)
memory usage: 49.0+ KB

In [6]:
x = df.drop('diagnosis', axis = 1)
y = df['diagnosis']

In [7]:
x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883
...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 2)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
clf=GridSearchCV(SVC(gamma='auto'),
 {'C':[1,10,20,30],
  'kernel':['rbf','linear']},
  cv=5)
clf.fit(x_train,y_train)
clf.cv_results_

{'mean_fit_time': array([0.00906553, 0.3911015 , 0.009445  , 2.76649222, 0.00929794,
        5.13544064, 0.00947294, 2.62716622]),
 'std_fit_time': array([3.70416134e-04, 1.43129122e-01, 6.19203784e-04, 7.11486755e-01,
        2.84994707e-04, 3.25468584e+00, 2.31852260e-04, 5.35647822e-01]),
 'mean_score_time': array([0.00407748, 0.00241895, 0.00392923, 0.00245242, 0.00387654,
        0.00241337, 0.00403385, 0.00261598]),
 'std_score_time': array([2.66199032e-04, 4.09406841e-05, 9.06427930e-05, 6.77923263e-05,
        6.14386868e-05, 7.99860186e-05, 1.07232864e-04, 3.68140318e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.675 , 0.8625, 0.65  , 0.85  , 0.65  , 0.85  , 0.65  , 0.85  ]),
 'split1_test_score': array([0.6375, 0.9625, 0.6625, 0.9875, 0.6625, 0.975 , 0.6625, 0.9625]),
 'split2_test_score': array([0.7125, 0.925 , 0.7125, 0.925 , 0.7125, 0.9125, 0.7125, 0.925 ]),
 'split3_test_score': array([0.65822785, 0.91139241, 0.67088608, 0.91139241, 0.67088608,
        0.93670886, 0.67088608, 0.93670886]),
 'split4_test_score': array([0.64556962, 0.89873418, 0.62025316, 0.88607595, 0.62025316,
        0.89873418, 0.62025316, 0.91139241]),
 'mean_test_score': array([0.66575949, 0.91202532, 0.66322785, 0.91199367, 0.66322785,
        0.91458861, 0.66322785, 0.91712025]),
 'std_test_score': array([0.02658201, 0.03269816, 0.03002906, 0.0455756 , 0.03002906,
        0.04139144, 0.03002906, 0.03753149]),
 'rank_test_score': array([5, 3, 6, 4, 6, 2, 6, 1], dtype=int32)}

In [10]:
df =pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009066,0.000370,0.004077,0.000266,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.6750,0.6375,0.7125,0.658228,0.645570,0.665759,0.026582,5
1,0.391102,0.143129,0.002419,0.000041,1,linear,"{'C': 1, 'kernel': 'linear'}",0.8625,0.9625,0.9250,0.911392,0.898734,0.912025,0.032698,3
2,0.009445,0.000619,0.003929,0.000091,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.6500,0.6625,0.7125,0.670886,0.620253,0.663228,0.030029,6
3,2.766492,0.711487,0.002452,0.000068,10,linear,"{'C': 10, 'kernel': 'linear'}",0.8500,0.9875,0.9250,0.911392,0.886076,0.911994,0.045576,4
4,0.009298,0.000285,0.003877,0.000061,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.6500,0.6625,0.7125,0.670886,0.620253,0.663228,0.030029,6
5,5.135441,3.254686,0.002413,0.000080,20,linear,"{'C': 20, 'kernel': 'linear'}",0.8500,0.9750,0.9125,0.936709,0.898734,0.914589,0.041391,2
6,0.009473,0.000232,0.004034,0.000107,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.6500,0.6625,0.7125,0.670886,0.620253,0.663228,0.030029,6
7,2.627166,0.535648,0.002616,0.000368,30,linear,"{'C': 30, 'kernel': 'linear'}",0.8500,0.9625,0.9250,0.936709,0.911392,0.917120,0.037531,1

In [11]:
clf.best_params_

{'C': 30, 'kernel': 'linear'}

In [12]:
clf.best_score_

np.float64(0.9171202531645569)

In [15]:
svm_model = SVC(kernel='linear',C=30,gamma='auto')
svm_model.fit(x_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [17]:
svm_model.score(x_test, y_test)

0.9239766081871345

In [18]:
svm_model.predict([[1.740, 1.91, 10.12, 585.0, 0.07944, 0.06376, 1.02881, 0.01329, 0.1473, 2.05580]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array(['M'], dtype=object)

In [20]:
predictions = svm_model.predict(x_test)
predictions

array(['B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B'], dtype=object)

In [27]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

x_after_min_max_scaler = MMS.fit_transform(x_train)

x_after_min_max_scaler

array([[0.18684867, 0.        , 0.17455104, ..., 0.08439364, 0.12305923,
        0.30661717],
       [0.30818533, 0.13561042, 0.29348054, ..., 0.14234592, 0.25876941,
        0.1305962 ],
       [0.37227849, 0.43862022, 0.36754944, ..., 0.18568588, 0.16503738,
        0.25136493],
       ...,
       [0.26806595, 0.10551234, 0.24484662, ..., 0.05710736, 0.25646924,
        0.2221009 ],
       [0.26219482, 0.08657423, 0.24561526, ..., 0.13156064, 0.30017251,
        0.1773313 ],
       [0.51318558, 0.50625634, 0.50527566, ..., 0.51838966, 0.213341  ,
        0.29897358]])

In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_after_min_max_scaler, y_train)

KNeighborsClassifier()

In [30]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

x_Test_Scaled = MMS.fit_transform(x_test)

x_Test_Scaled

array([[0.30603849, 0.11576355, 0.29944349, ..., 0.34579195, 0.46262626,
        0.29914712],
       [0.35599197, 0.40788177, 0.3473887 , ..., 0.251908  , 0.41363636,
        0.17014925],
       [0.09682159, 0.35862069, 0.09075342, ..., 0.03015682, 0.31313131,
        0.28955224],
       ...,
       [0.2080905 , 0.36551724, 0.19527683, ..., 0.07051751, 0.40808081,
        0.22515991],
       [0.22131348, 0.16108374, 0.21718037, ..., 0.1324621 , 0.2959596 ,
        0.23454158],
       [0.31877173, 0.47832512, 0.31442637, ..., 0.15985363, 0.22525253,
        0.20362473]])

In [31]:
knn.score(x_Test_Scaled, y_test)

0.9298245614035088